# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install Python dependencies and set up application
RUN pip install --upgrade pip
WORKDIR /app
COPY pyproject.toml src/ LICENSE README.md TOOLS.md .
# Copy other necessary files and directories
COPY src ./src

# Install application
RUN pip install . --no-cache-dir

# Default command for stdio transport
CMD ["excel-mcp-server", "stdio"]
